# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui/mainwindow.ui'
#
# Created: Tue Aug  5 17:31:33 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 645)
        MainWindow.setStyleSheet("QMenuBar { \n"
"    background-color: rgb(197, 197, 197);\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: rgb(197, 197, 197);\n"
"    color: black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAdvanced = QtWidgets.QMenu(self.menubar)
        self.menuAdvanced.setObjectName("menuAdvanced")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_segment = QtWidgets.QWidget()
        self.tab_segment.setObjectName("tab_segment")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_segment)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_open_ct_dura = QtWidgets.QPushButton(self.tab_segment)
        self.pushButton_open_ct_dura.setAutoDefault(False)
        self.pushButton_open_ct_dura.setDefault(False)
        self.pushButton_open_ct_dura.setObjectName("pushButton_open_ct_dura")
        self.verticalLayout_7.addWidget(self.pushButton_open_ct_dura)
        self.frame_segment = QtWidgets.QFrame(self.tab_segment)
        self.frame_segment.setEnabled(False)
        self.frame_segment.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_segment.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_segment.setLineWidth(2)
        self.frame_segment.setObjectName("frame_segment")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_segment)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame_segment)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_threshold = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_threshold.setObjectName("horizontalSlider_threshold")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_threshold)
        self.spinBox_threshold = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_threshold.setObjectName("spinBox_threshold")
        self.horizontalLayout_2.addWidget(self.spinBox_threshold)
        self.verticalLayout.addWidget(self.groupBox)
        self.pushButton_preview_threshold = QtWidgets.QPushButton(self.frame_segment)
        self.pushButton_preview_threshold.setObjectName("pushButton_preview_threshold")
        self.verticalLayout.addWidget(self.pushButton_preview_threshold)
        self.pushButton_hide_preview = QtWidgets.QPushButton(self.frame_segment)
        self.pushButton_hide_preview.setEnabled(False)
        self.pushButton_hide_preview.setObjectName("pushButton_hide_preview")
        self.verticalLayout.addWidget(self.pushButton_hide_preview)
        self.verticalLayout_7.addWidget(self.frame_segment)
        self.frame_segment_config = QtWidgets.QFrame(self.tab_segment)
        self.frame_segment_config.setEnabled(False)
        self.frame_segment_config.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_segment_config.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_segment_config.setObjectName("frame_segment_config")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_segment_config)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_heuristic_distance = QtWidgets.QGroupBox(self.frame_segment_config)
        self.groupBox_heuristic_distance.setObjectName("groupBox_heuristic_distance")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_heuristic_distance)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider_distance = QtWidgets.QSlider(self.groupBox_heuristic_distance)
        self.horizontalSlider_distance.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_distance.setInvertedControls(False)
        self.horizontalSlider_distance.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_distance.setObjectName("horizontalSlider_distance")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_distance)
        self.doubleSpinBox_distance = QtWidgets.QDoubleSpinBox(self.groupBox_heuristic_distance)
        self.doubleSpinBox_distance.setObjectName("doubleSpinBox_distance")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_distance)
        self.label = QtWidgets.QLabel(self.groupBox_heuristic_distance)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_6.addWidget(self.groupBox_heuristic_distance)
        self.groupBox_heuristic_size = QtWidgets.QGroupBox(self.frame_segment_config)
        self.groupBox_heuristic_size.setObjectName("groupBox_heuristic_size")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_heuristic_size)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalSlider_size = QtWidgets.QSlider(self.groupBox_heuristic_size)
        self.horizontalSlider_size.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_size.setObjectName("horizontalSlider_size")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_size)
        self.doubleSpinBox_size = QtWidgets.QDoubleSpinBox(self.groupBox_heuristic_size)
        self.doubleSpinBox_size.setObjectName("doubleSpinBox_size")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_size)
        self.label_2 = QtWidgets.QLabel(self.groupBox_heuristic_size)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_6.addWidget(self.groupBox_heuristic_size)
        self.verticalLayout_7.addWidget(self.frame_segment_config)
        self.pushButton_segment = QtWidgets.QPushButton(self.tab_segment)
        self.pushButton_segment.setEnabled(False)
        self.pushButton_segment.setObjectName("pushButton_segment")
        self.verticalLayout_7.addWidget(self.pushButton_segment)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_segment, "")
        self.tab_edit = QtWidgets.QWidget()
        self.tab_edit.setEnabled(False)
        self.tab_edit.setObjectName("tab_edit")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_edit)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeView_edit = QtWidgets.QTreeView(self.tab_edit)
        self.treeView_edit.setAlternatingRowColors(True)
        self.treeView_edit.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeView_edit.setObjectName("treeView_edit")
        self.verticalLayout_2.addWidget(self.treeView_edit)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_edit_select_count = QtWidgets.QLabel(self.tab_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_edit_select_count.sizePolicy().hasHeightForWidth())
        self.label_edit_select_count.setSizePolicy(sizePolicy)
        self.label_edit_select_count.setObjectName("label_edit_select_count")
        self.horizontalLayout_9.addWidget(self.label_edit_select_count)
        self.label_6 = QtWidgets.QLabel(self.tab_edit)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_edit_electrode_count = QtWidgets.QLabel(self.tab_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_edit_electrode_count.sizePolicy().hasHeightForWidth())
        self.label_edit_electrode_count.setSizePolicy(sizePolicy)
        self.label_edit_electrode_count.setText("")
        self.label_edit_electrode_count.setObjectName("label_edit_electrode_count")
        self.horizontalLayout_7.addWidget(self.label_edit_electrode_count)
        self.label_7 = QtWidgets.QLabel(self.tab_edit)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_component_count = QtWidgets.QLabel(self.tab_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_component_count.sizePolicy().hasHeightForWidth())
        self.label_component_count.setSizePolicy(sizePolicy)
        self.label_component_count.setText("")
        self.label_component_count.setObjectName("label_component_count")
        self.horizontalLayout_7.addWidget(self.label_component_count)
        self.label_5 = QtWidgets.QLabel(self.tab_edit)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(self.tab_edit)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.pushButton_add = QtWidgets.QPushButton(self.tab_edit)
        self.pushButton_add.setCheckable(True)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout_2.addWidget(self.pushButton_add)
        self.pushButton_import_point_set = QtWidgets.QPushButton(self.tab_edit)
        self.pushButton_import_point_set.setObjectName("pushButton_import_point_set")
        self.verticalLayout_2.addWidget(self.pushButton_import_point_set)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_remove = QtWidgets.QPushButton(self.tab_edit)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.horizontalLayout_10.addWidget(self.pushButton_remove)
        self.pushButton_restore = QtWidgets.QPushButton(self.tab_edit)
        self.pushButton_restore.setObjectName("pushButton_restore")
        self.horizontalLayout_10.addWidget(self.pushButton_restore)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tab_edit)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.spinBox_split = QtWidgets.QSpinBox(self.tab_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_split.sizePolicy().hasHeightForWidth())
        self.spinBox_split.setSizePolicy(sizePolicy)
        self.spinBox_split.setMinimum(2)
        self.spinBox_split.setObjectName("spinBox_split")
        self.horizontalLayout_5.addWidget(self.spinBox_split)
        self.pushButton_split = QtWidgets.QPushButton(self.tab_edit)
        self.pushButton_split.setObjectName("pushButton_split")
        self.horizontalLayout_5.addWidget(self.pushButton_split)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.pushButton_clear = QtWidgets.QPushButton(self.tab_edit)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout_2.addWidget(self.pushButton_clear)
        self.tabWidget.addTab(self.tab_edit, "")
        self.tab_label = QtWidgets.QWidget()
        self.tab_label.setEnabled(False)
        self.tab_label.setObjectName("tab_label")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_label)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView_label = QtWidgets.QTableView(self.tab_label)
        self.tableView_label.setAlternatingRowColors(True)
        self.tableView_label.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_label.setSortingEnabled(True)
        self.tableView_label.setObjectName("tableView_label")
        self.verticalLayout_5.addWidget(self.tableView_label)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.label_label_select_count = QtWidgets.QLabel(self.tab_label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_label_select_count.sizePolicy().hasHeightForWidth())
        self.label_label_select_count.setSizePolicy(sizePolicy)
        self.label_label_select_count.setObjectName("label_label_select_count")
        self.horizontalLayout_12.addWidget(self.label_label_select_count)
        self.label_10 = QtWidgets.QLabel(self.tab_label)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_grid_label = QtWidgets.QLineEdit(self.tab_label)
        self.lineEdit_grid_label.setObjectName("lineEdit_grid_label")
        self.horizontalLayout_8.addWidget(self.lineEdit_grid_label)
        self.pushButton_assign_grid_label = QtWidgets.QPushButton(self.tab_label)
        self.pushButton_assign_grid_label.setObjectName("pushButton_assign_grid_label")
        self.horizontalLayout_8.addWidget(self.pushButton_assign_grid_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.pushButton_label_clear = QtWidgets.QPushButton(self.tab_label)
        self.pushButton_label_clear.setObjectName("pushButton_label_clear")
        self.verticalLayout_5.addWidget(self.pushButton_label_clear)
        self.pushButton_export = QtWidgets.QPushButton(self.tab_label)
        self.pushButton_export.setObjectName("pushButton_export")
        self.verticalLayout_5.addWidget(self.pushButton_export)
        self.tabWidget.addTab(self.tab_label, "")
        self.tab_register = QtWidgets.QWidget()
        self.tab_register.setEnabled(False)
        self.tab_register.setObjectName("tab_register")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_register)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listView_register = QtWidgets.QListView(self.tab_register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_register.sizePolicy().hasHeightForWidth())
        self.listView_register.setSizePolicy(sizePolicy)
        self.listView_register.setAlternatingRowColors(True)

        #  Cont
        self.listView_register.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView_register.setObjectName("listView_register")
        self.verticalLayout_4.addWidget(self.listView_register)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label_register_select_count = QtWidgets.QLabel(self.tab_register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_register_select_count.sizePolicy().hasHeightForWidth())
        self.label_register_select_count.setSizePolicy(sizePolicy)
        self.label_register_select_count.setObjectName("label_register_select_count")
        self.horizontalLayout_6.addWidget(self.label_register_select_count)
        self.label_8 = QtWidgets.QLabel(self.tab_register)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_register_complete_count = QtWidgets.QLabel(self.tab_register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_register_complete_count.sizePolicy().hasHeightForWidth())
        self.label_register_complete_count.setSizePolicy(sizePolicy)
        self.label_register_complete_count.setObjectName("label_register_complete_count")
        self.horizontalLayout_11.addWidget(self.label_register_complete_count)
        self.label_9 = QtWidgets.QLabel(self.tab_register)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.label_register_electrode_count = QtWidgets.QLabel(self.tab_register)
        self.label_register_electrode_count.setObjectName("label_register_electrode_count")
        self.horizontalLayout_11.addWidget(self.label_register_electrode_count)
        self.label_4 = QtWidgets.QLabel(self.tab_register)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_svd = QtWidgets.QPushButton(self.tab_register)
        self.pushButton_svd.setObjectName("pushButton_svd")
        self.gridLayout.addWidget(self.pushButton_svd, 1, 0, 1, 1)
        self.pushButton_manual = QtWidgets.QPushButton(self.tab_register)
        self.pushButton_manual.setCheckable(True)
        self.pushButton_manual.setChecked(False)
        self.pushButton_manual.setObjectName("pushButton_manual")
        self.gridLayout.addWidget(self.pushButton_manual, 1, 1, 1, 1)
        self.pushButton_nearest = QtWidgets.QPushButton(self.tab_register)
        self.pushButton_nearest.setObjectName("pushButton_nearest")
        self.gridLayout.addWidget(self.pushButton_nearest, 0, 1, 1, 1)
        self.pushButton_principal = QtWidgets.QPushButton(self.tab_register)
        self.pushButton_principal.setObjectName("pushButton_principal")
        self.gridLayout.addWidget(self.pushButton_principal, 0, 0, 1, 1)
        self.pushButton_unregister = QtWidgets.QPushButton(self.tab_register)
        self.pushButton_unregister.setObjectName("pushButton_unregister")
        self.gridLayout.addWidget(self.pushButton_unregister, 2, 0, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.pushButton_register_clear = QtWidgets.QPushButton(self.tab_register)
        self.pushButton_register_clear.setObjectName("pushButton_register_clear")
        self.verticalLayout_4.addWidget(self.pushButton_register_clear)
        self.tabWidget.addTab(self.tab_register, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpenProject = QtGui.QAction(MainWindow)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.actionSaveProject = QtGui.QAction(MainWindow)
        self.actionSaveProject.setObjectName("actionSaveProject")
        self.actionRecentProjects = QtGui.QAction(MainWindow)
        self.actionRecentProjects.setObjectName("actionRecentProjects")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSaveProjectAs = QtGui.QAction(MainWindow)
        self.actionSaveProjectAs.setObjectName("actionSaveProjectAs")
        self.actionOpenPial = QtGui.QAction(MainWindow)
        self.actionOpenPial.setObjectName("actionOpenPial")
        self.actionShowPial = QtGui.QAction(MainWindow)
        self.actionShowPial.setCheckable(True)
        self.actionShowPial.setObjectName("actionShowPial")
        self.actionHideThresholdingPreview = QtGui.QAction(MainWindow)
        self.actionHideThresholdingPreview.setObjectName("actionHideThresholdingPreview")
        self.actionExport_segmentation_dataset = QtGui.QAction(MainWindow)
        self.actionExport_segmentation_dataset.setObjectName("actionExport_segmentation_dataset")
        self.actionShow_Electrode_ID = QtGui.QAction(MainWindow)
        self.actionShow_Electrode_ID.setCheckable(True)
        self.actionShow_Electrode_ID.setObjectName("actionShow_Electrode_ID")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionReport_an_issue = QtGui.QAction(MainWindow)
        self.actionReport_an_issue.setObjectName("actionReport_an_issue")
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionSource_Repository = QtGui.QAction(MainWindow)
        self.actionSource_Repository.setObjectName("actionSource_Repository")
        self.actionLicense = QtGui.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpenPial)
        self.menuFile.addAction(self.actionOpenProject)
        self.menuFile.addAction(self.actionSaveProject)
        self.menuFile.addAction(self.actionSaveProjectAs)
        self.menuFile.addAction(self.actionRecentProjects)
        self.menuHelp.addAction(self.actionReport_an_issue)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionSource_Repository)
        self.menuHelp.addAction(self.actionLicense)
        self.menuView.addAction(self.actionShowPial)
        self.menuView.addAction(self.actionHideThresholdingPreview)
        self.menuView.addAction(self.actionShow_Electrode_ID)
        self.menuAdvanced.addAction(self.actionExport_segmentation_dataset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAdvanced.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.horizontalSlider_threshold, QtCore.SIGNAL("sliderMoved(int)"),
                               self.spinBox_threshold.setValue)
        QtCore.QObject.connect(self.pushButton_open_ct_dura, QtCore.SIGNAL("clicked()"), self.actionOpen.trigger)
        QtCore.QObject.connect(self.spinBox_threshold, QtCore.SIGNAL("valueChanged(int)"),
                               self.horizontalSlider_threshold.setValue)
        QtCore.QObject.connect(self.pushButton_hide_preview, QtCore.SIGNAL("clicked()"),
                               self.actionHideThresholdingPreview.trigger)
        QtCore.QObject.connect(self.pushButton_clear, QtCore.SIGNAL("clicked()"), self.treeView_edit.clearSelection)
        QtCore.QObject.connect(self.pushButton_register_clear, QtCore.SIGNAL("clicked()"),
                               self.listView_register.clearSelection)
        QtCore.QObject.connect(self.pushButton_label_clear, QtCore.SIGNAL("clicked()"),
                               self.tableView_label.clearSelection)
        QtCore.QObject.connect(self.lineEdit_grid_label, QtCore.SIGNAL("returnPressed()"),
                               self.pushButton_assign_grid_label.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Interactive Electrode Registration"))
            self.menuFile.setTitle(_translate("MainWindow", "File"))
            self.menuHelp.setTitle(_translate("MainWindow", "Help"))
            self.menuView.setTitle(_translate("MainWindow", "View"))
            self.menuAdvanced.setTitle(_translate("MainWindow", "Advanced"))
            self.pushButton_open_ct_dura.setText(_translate("MainWindow", "Open CT and Dura..."))
            self.groupBox.setToolTip(_translate("MainWindow", "lower bound on a connected component's CT intensity"))
            self.groupBox.setTitle(_translate("MainWindow", "Threshold"))
            self.pushButton_preview_threshold.setText(_translate("MainWindow", "Preview Thresholding"))
            self.pushButton_hide_preview.setText(_translate("MainWindow", "Hide Preview"))
            self.groupBox_heuristic_distance.setToolTip(
                    _translate("MainWindow", "upper bound on a connected component's distance to dura"))
            self.groupBox_heuristic_distance.setTitle(_translate("MainWindow", "Distance"))
            self.label.setText(_translate("MainWindow", "mm"))
            self.groupBox_heuristic_size.setToolTip(
                    _translate("MainWindow", "lower bound on a connected component's size"))
            self.groupBox_heuristic_size.setTitle(_translate("MainWindow", "Size"))
            self.label_2.setText(_translate("MainWindow", "mm<sup>3</sup>"))
            self.pushButton_segment.setText(_translate("MainWindow", "Segment"))
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_segment), _translate("MainWindow", "Segment"))
            self.label_edit_select_count.setText(_translate("MainWindow", "0"))
            self.label_6.setText(_translate("MainWindow", "Selected"))
            self.label_7.setText(_translate("MainWindow", "Electrodes"))
            self.label_5.setText(_translate("MainWindow", "Components"))
            self.pushButton_add.setText(_translate("MainWindow", "&Add"))
            self.pushButton_add.setShortcut(_translate("MainWindow", "A"))
            self.pushButton_import_point_set.setText(_translate("MainWindow", "&Import from Point Set..."))
            self.pushButton_import_point_set.setShortcut(_translate("MainWindow", "I"))
            self.pushButton_remove.setText(_translate("MainWindow", "Remove"))
            self.pushButton_remove.setShortcut(_translate("MainWindow", "Del"))
            self.pushButton_restore.setText(_translate("MainWindow", "Restore"))
            self.pushButton_restore.setShortcut(_translate("MainWindow", "Shift+Del"))
            self.label_3.setText(_translate("MainWindow", "Pieces"))
            self.pushButton_split.setText(_translate("MainWindow", "&Split"))
            self.pushButton_split.setShortcut(_translate("MainWindow", "S"))
            self.pushButton_clear.setText(_translate("MainWindow", "&Clear Selection"))
            self.pushButton_clear.setShortcut(_translate("MainWindow", "C"))
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_edit), _translate("MainWindow", "Edit"))
            self.label_label_select_count.setText(_translate("MainWindow", "0"))
            self.label_10.setText(_translate("MainWindow", "Selected"))
            self.pushButton_assign_grid_label.setText(_translate("MainWindow", "&Assign Grid Label"))
            self.pushButton_assign_grid_label.setShortcut(_translate("MainWindow", "A"))
            self.pushButton_label_clear.setText(_translate("MainWindow", "&Clear Selection"))
            self.pushButton_label_clear.setShortcut(_translate("MainWindow", "C"))
            self.pushButton_export.setText(_translate("MainWindow", "&Export..."))
            self.pushButton_export.setShortcut(_translate("MainWindow", "E"))
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_label), _translate("MainWindow", "Label"))
            self.label_register_select_count.setText(_translate("MainWindow", "0"))
            self.label_8.setText(_translate("MainWindow", "Selected"))
            self.label_register_complete_count.setText(_translate("MainWindow", "0"))
            self.label_9.setText(_translate("MainWindow", "Registered"))
            self.label_register_electrode_count.setText(_translate("MainWindow", "0"))
            self.label_4.setText(_translate("MainWindow", "Electrodes"))
            self.pushButton_svd.setText(_translate("MainWindow", "&Best-fit Plane"))
            self.pushButton_svd.setShortcut(_translate("MainWindow", "B"))
            self.pushButton_manual.setToolTip(
                    _translate("MainWindow", "right click to register; only supports single selection"))
            self.pushButton_manual.setText(_translate("MainWindow", "&Manual"))
            self.pushButton_manual.setShortcut(_translate("MainWindow", "M"))
            self.pushButton_nearest.setText(_translate("MainWindow", "&Nearest Vertex"))
            self.pushButton_nearest.setShortcut(_translate("MainWindow", "N"))
            self.pushButton_principal.setText(_translate("MainWindow", "&Principal Axis"))
            self.pushButton_principal.setShortcut(_translate("MainWindow", "P"))
            self.pushButton_unregister.setText(_translate("MainWindow", "&Unregister"))
            self.pushButton_unregister.setShortcut(_translate("MainWindow", "U"))
            self.pushButton_register_clear.setText(_translate("MainWindow", "&Clear Selection"))
            self.pushButton_register_clear.setShortcut(_translate("MainWindow", "C"))
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_register), _translate("MainWindow", "Register"))
            self.actionOpen.setText(_translate("MainWindow", "Open CT/dura..."))
            self.actionOpenProject.setText(_translate("MainWindow", "Open Project..."))
            self.actionSaveProject.setText(_translate("MainWindow", "Save Project"))
            self.actionSaveProject.setShortcut(_translate("MainWindow", "Ctrl+S"))
            self.actionRecentProjects.setText(_translate("MainWindow", "Recent Projects"))
            self.actionAbout.setText(_translate("MainWindow", "About"))
            self.actionSaveProjectAs.setText(_translate("MainWindow", "Save Project As..."))
            self.actionOpenPial.setText(_translate("MainWindow", "Open Pial..."))
            self.actionShowPial.setText(_translate("MainWindow", "Show Pial"))
            self.actionHideThresholdingPreview.setText(_translate("MainWindow", "Hide Thresholding Preview"))
            self.actionExport_segmentation_dataset.setText(_translate("MainWindow", "Export Segmentation Dataset"))
            self.actionShow_Electrode_ID.setText(_translate("MainWindow", "Show Electrode ID"))
            self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
            self.actionReport_an_issue.setText(_translate("MainWindow", "Report an Issue..."))
            self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
            self.actionSource_Repository.setText(_translate("MainWindow", "Source Repository"))
            self.actionLicense.setText(_translate("MainWindow", "License"))